apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: promtail
      version: "6.15.3"
      sourceRef:
        kind: HelmRepository
        name: grafana-repo
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: promtail-values