---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-local-config-yaml
  namespace: monitoring
data:
  # Archivo de configuración principal de Loki, utilizado en modo local
  local-config.yaml: |
    # Desactiva la autenticación (útil para entornos de desarrollo o clústeres internos)
    auth_enabled: false

    server:
      # Puerto en el que Loki escuchará conexiones HTTP
      http_listen_port: 3100

    ingester:
      lifecycler:
        # Dirección local para el ring de ingesters
        address: 127.0.0.1
        ring:
          kvstore:
            # Utiliza almacenamiento en memoria para el ring (no persistente)
            store: inmemory
          # Número de réplicas de cada log (1 para modo single-node)
          replication_factor: 1
        # Tiempo de espera final antes de cerrar un ingester al detenerse
        final_sleep: 0s
      # Tiempo de inactividad tras el cual se cierra un chunk no usado
      chunk_idle_period: 5m
      # Tiempo durante el cual se retiene un chunk en memoria antes de desecharlo
      chunk_retain_period: 30s

    schema_config:
      configs:
        - from: 2020-05-15
          # Motor de almacenamiento de índice: boltdb (local y sencillo)
          store: boltdb
          # Almacenamiento de objetos (los chunks de logs): filesystem local
          object_store: filesystem
          # Esquema de almacenamiento utilizado (v11 es estable)
          schema: v11
          index:
            # Prefijo usado para los archivos de índice
            prefix: index_
            # Cada cuánto tiempo se rota el índice (168h = 7 días)
            period: 168h

    storage_config:
      boltdb:
        # Carpeta donde se guardan los índices
        directory: /tmp/loki/index

      filesystem:
        # Carpeta donde se guardan los chunks (datos reales de los logs)
        directory: /tmp/loki/chunks

    limits_config:
      # Permite recibir logs sin nombre de métrica (importante para Loki)
      enforce_metric_name: false
      # Rechaza muestras de log demasiado antiguas
      reject_old_samples: true
      # Tiempo máximo de antigüedad permitido para las muestras
      reject_old_samples_max_age: 168h
