apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: "5.41.4"  
      sourceRef:
        kind: HelmRepository
        name: grafana-repo
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: loki-values