
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-values
  namespace: monitoring
data:
  values.yaml: |
    loki:
      auth_enabled: false

      server:
        http_listen_port: 3100

      ingester:
        lifecycler:
          address: 127.0.0.1
          ring:
            kvstore:
              store: inmemory
            replication_factor: 1
          final_sleep: 0s
        chunk_idle_period: 5m
        max_chunk_age: 1h
        chunk_retain_period: 30s
        wal:
          enabled: true
          dir: /var/loki/wal

      schema_config:
        configs:
          - from: "2022-01-01"
            store: boltdb
            object_store: filesystem
            schema: v11
            index:
              prefix: index_
              period: 168h

      storage_config:
        boltdb:
          directory: /var/loki/index
        filesystem:
          directory: /var/loki/chunks

      compactor:
        working_directory: /var/loki/compactor
        shared_store: filesystem

      limits_config:
        retention_period: 168h

    persistence:
      enabled: true
      size: 10Gi
      accessModes:
        - ReadWriteOnce
      storageClassName: do-block-storage

    service:
      type: ClusterIP
      port: 3100
