---
apiVersion: v1
kind: Service
metadata:
  name: loki-service                 # Nombre del Service para acceder a Loki dentro del clúster
  namespace: monitoring              # Namespace en el que se encuentra el Service y el Deployment de Loki
  labels:
    app: loki                        # Etiqueta que identifica el recurso como parte de Loki

spec:
  type: ClusterIP                   # Expone el servicio dentro del clúster (acceso interno entre pods)
  
  ports:
    - name: loki                    # Nombre del puerto (puede usarse en otras referencias)
      protocol: TCP                # Protocolo de red utilizado
      port: 3100                   # Puerto del servicio expuesto internamente en el clúster
      targetPort: 3100             # Puerto del contenedor Loki al que se redirige el tráfico

  selector:
    app: loki                      # Selecciona los pods con la etiqueta 'app: loki' (es decir, el Deployment de Loki)
